<?php

namespace MonSac\DeSportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function search($search)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where("LOWER(p.name) LIKE :search")
            ->where("LOWER(p.description) LIKE :search")
            ->setParameter('search', '%'.$search.'%');

        return $products = $qb->getQuery()->getResult();
    }
}
