<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140614170200 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user ADD first_name TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD last_name TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD address TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD zipcode TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD city TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD phone TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD complementary_info TEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user DROP first_name");
        $this->addSql("ALTER TABLE fos_user DROP last_name");
        $this->addSql("ALTER TABLE fos_user DROP address");
        $this->addSql("ALTER TABLE fos_user DROP zipcode");
        $this->addSql("ALTER TABLE fos_user DROP city");
        $this->addSql("ALTER TABLE fos_user DROP phone");
        $this->addSql("ALTER TABLE fos_user DROP complementary_info");
    }
}
