<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140614165836 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE TABLE product_commande (product_id INT NOT NULL, commande_id INT NOT NULL, PRIMARY KEY(product_id, commande_id))");
        $this->addSql("CREATE INDEX IDX_A55ACCEA4584665A ON product_commande (product_id)");
        $this->addSql("CREATE INDEX IDX_A55ACCEA82EA2E54 ON product_commande (commande_id)");
        $this->addSql("ALTER TABLE product_commande ADD CONSTRAINT FK_A55ACCEA4584665A FOREIGN KEY (product_id) REFERENCES Product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE product_commande ADD CONSTRAINT FK_A55ACCEA82EA2E54 FOREIGN KEY (commande_id) REFERENCES Commande (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE commande ADD customer_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE commande ADD CONSTRAINT FK_979CC42B9395C3F3 FOREIGN KEY (customer_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_979CC42B9395C3F3 ON commande (customer_id)");
        $this->addSql("ALTER TABLE fos_user ADD first_name TEXT NOT NULL");
        $this->addSql("ALTER TABLE fos_user ADD last_name TEXT NOT NULL");
        $this->addSql("ALTER TABLE fos_user ADD address TEXT NOT NULL");
        $this->addSql("ALTER TABLE fos_user ADD zipcode TEXT NOT NULL");
        $this->addSql("ALTER TABLE fos_user ADD city TEXT NOT NULL");
        $this->addSql("ALTER TABLE fos_user ADD phone TEXT NOT NULL");
        $this->addSql("ALTER TABLE fos_user ADD complementary_info TEXT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP TABLE product_commande");
        $this->addSql("ALTER TABLE Commande DROP CONSTRAINT FK_979CC42B9395C3F3");
        $this->addSql("DROP INDEX IDX_979CC42B9395C3F3");
        $this->addSql("ALTER TABLE Commande DROP customer_id");
        $this->addSql("ALTER TABLE fos_user DROP first_name");
        $this->addSql("ALTER TABLE fos_user DROP last_name");
        $this->addSql("ALTER TABLE fos_user DROP address");
        $this->addSql("ALTER TABLE fos_user DROP zipcode");
        $this->addSql("ALTER TABLE fos_user DROP city");
        $this->addSql("ALTER TABLE fos_user DROP phone");
        $this->addSql("ALTER TABLE fos_user DROP complementary_info");
    }
}
