<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140614134434 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE image ADD product_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE image ADD CONSTRAINT FK_4FC2B5B4584665A FOREIGN KEY (product_id) REFERENCES Product (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_4FC2B5B4584665A ON image (product_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Image DROP CONSTRAINT FK_4FC2B5B4584665A");
        $this->addSql("DROP INDEX IDX_4FC2B5B4584665A");
        $this->addSql("ALTER TABLE Image DROP product_id");
    }
}
