<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140606004401 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE Commande_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Product_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE ProductCategory_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE Commande (id INT NOT NULL, num_commande VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, sentAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Product (id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(128) NOT NULL, createdAt DATE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT NOT NULL, quantity INT NOT NULL, price DOUBLE PRECISION NOT NULL, brand VARCHAR(255) NOT NULL, size VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1CF73D31989D9B62 ON Product (slug)");
        $this->addSql("CREATE TABLE ProductCategory (id INT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE Commande_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Product_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE ProductCategory_id_seq CASCADE");
        $this->addSql("DROP TABLE Commande");
        $this->addSql("DROP TABLE Product");
        $this->addSql("DROP TABLE ProductCategory");
    }
}
