mon_sac_de_sport_front:
    resource: "@MonSacDeSportBundle/Resources/config/routing/front.yml"
    prefix:   /

mon_sac_de_sport_admin:
    resource: "@MonSacDeSportBundle/Resources/config/routing/admin.yml"
    prefix:   /admin