parameters:
#    mon_sac_de_sport.example.class: MonSac\DeSportBundle\Example

services:
    monsac_desport.redirection_after_login:
        class: MonSac\DeSportBundle\Authentification\UserRedirection
        arguments: [@router]