admin_products:
    pattern:  /products
    defaults: { _controller: "MonSacDeSportBundle:Product:indexAdmin" }

admin_product_new:
    pattern:  /products/new
    defaults: { _controller: "MonSacDeSportBundle:Product:new" }

admin_product_create:
    pattern:  /products/create
    defaults: { _controller: "MonSacDeSportBundle:Product:create" }
    requirements: { _method: post }

admin_product_edit:
    pattern:  /products/{id}/edit
    defaults: { _controller: "MonSacDeSportBundle:Product:edit" }

admin_product_update:
    pattern:  /products/{id}/update
    defaults: { _controller: "MonSacDeSportBundle:Product:update" }
    requirements: { _method: post|put }

admin_product_delete:
    pattern:  /products/{id}/delete
    defaults: { _controller: "MonSacDeSportBundle:Product:delete" }
    requirements: { _method: post|delete }

admin_product_search:
    pattern:  /products/search
    defaults:  { _controller: MonSacDeSportBundle:Product:searchAdmin }
    requirements: { _method: get }

admin_commandes:
    pattern:  /commandes/status-{status}
    defaults: { _controller: "MonSacDeSportBundle:Commande:index", status: 0 }
    requirements:
        status: '[0-4]'

admin_commande_show:
    pattern: /commandes/{id}
    defaults: { _controller: MonSacDeSportBundle:Commande:adminShow }
    requirements:
        id: \d+

admin_commande_update_status:
    pattern: /commandes/{id}/update-status
    defaults: { _controller: MonSacDeSportBundle:Commande:updateStatus }
    requirements:
        id: \d+
        _method: post|put

admin_users:
    pattern:  /comptes-client
    defaults:  { _controller: MonSacDeSportBundle:User:index }

admin_user_commandes:
    pattern:  /comptes-client/{id}/commandes
    defaults:  { _controller: MonSacDeSportBundle:User:commandes }
