front_category_product:
    pattern: /{productCategorySlug}
    defaults: { _controller: "MonSacDeSportBundle:Product:productByCategory" }

front_product_show:
    pattern:  /{productCategorySlug}/{productSlug}
    defaults: { _controller: "MonSacDeSportBundle:Product:show" }