mon_sac_de_sport_articles:
    resource: "@MonSacDeSportBundle/Resources/config/routing/articles.yml"
    prefix:   /articles

front_commande_show:
    pattern:  /commandes/{id}
    defaults: { _controller: "MonSacDeSportBundle:Commande:show" }
    requirements: { _method: get }

front_commande_new:
    pattern:  /commandes/new
    defaults: { _controller: "MonSacDeSportBundle:Commande:new" }